import {
  Table,
  TableBody,
  TableCell,
  TableColumn,
  TableHeader,
  TableRow,
} from "@nextui-org/react";
import { Persona } from "../../data-autogenerated/data-febrauary-2024";

export default function EmployersTable({ people }: { people: Persona[] }) {
  return (
    <Table
      aria-label="Example static collection table"
      className="overflow-auto h-full"
    >
      <TableHeader>
        <TableColumn>NOMBRE</TableColumn>
        <TableColumn>CEDULA</TableColumn>
        <TableColumn>AUSENTE</TableColumn>
      </TableHeader>
      <TableBody>
        {people.map(({ absent, id, name }, index) => (
          <TableRow key={index}>
            <TableCell>{name}</TableCell>
            <TableCell>{id}</TableCell>
            <TableCell>
              {absent ? (
                <span className="bg-red-200 rounded-xl p-1">Ausente</span>
              ) : (
                <span className="bg-green-200 rounded-xl p-1">Presente</span>
              )}
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
