import {
  Table,
  TableBody,
  TableCell,
  TableColumn,
  TableHeader,
  TableRow,
} from "@nextui-org/react";
import { Persona } from "../../data-autogenerated/data-febrauary-2024";

export default function EmployersTable({
  people,
}: Readonly<{ people: Persona[] }>) {
  return (
    <Table
      aria-label="Example static collection table"
      className="overflow-auto h-full"
      shadow="none"
      isHeaderSticky
    >
      <TableHeader>
        <TableColumn>NOMBRE</TableColumn>
        <TableColumn>CEDULA</TableColumn>
        <TableColumn>AUSENTE</TableColumn>
      </TableHeader>
      <TableBody>
        {people.map(({ absent, id, name }, index) => (
          <TableRow key={id + index}>
            <TableCell>{name}</TableCell>
            <TableCell>{id}</TableCell>
            <TableCell>
              {absent ? (
                <span className="bg-red-400 rounded-xl py-1 px-2 text-red-100">
                  Ausente
                </span>
              ) : (
                <span className="bg-green-400 rounded-xl py-1 px-2 text-green-100">
                  Presente
                </span>
              )}
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
