import { ScrollShadow } from "@nextui-org/react";
import EmployersTable from "./tables/EmployersTable";
import clsx from "clsx";
import {
  getDateNow,
  getDaysInMonthWithWeekday,
} from "../utils/dates-functions";
import { generarDatos } from "../data-autogenerated/data-febrauary-2024";
import { useAtom } from "jotai";
import { selectedDayAtom } from "../atoms/dayAtoms";

function Date({
  day,
  numberDay,
  selected,
  weekDayNumber,
  changeSelected,
}: {
  day: string;
  numberDay: number;
  selected: boolean;
  weekDayNumber: number;
  changeSelected: (day: number) => void;
}) {
  return (
    <div
      className={clsx(
        "relative flex h-full flex-col align-middle items-center text-center shadow-md p-1 rounded-xl",
        { "bg-[#bec2c9] outline-blue-200 outline outline-2": selected },
        {
          "bg-red-400": weekDayNumber === 0,
        }
      )}
      onClick={() => changeSelected(numberDay)}
    >
      <h6
        className={clsx({
          "text-white": weekDayNumber === 0,
          "text-gray-500": weekDayNumber !== 0,
        })}
      >
        {day.slice(0, 3)}.
      </h6>
      <p className="font-bold">{numberDay}</p>
    </div>
  );
}

function DatesContainer() {
  const { monthNow, yearNow } = getDateNow();
  const daysInMonth = getDaysInMonthWithWeekday(yearNow, monthNow);
  const [selectedDay, setSelectedDay] = useAtom(selectedDayAtom);

  console.log(daysInMonth);
  return (
    <ScrollShadow
      orientation="horizontal"
      className="w-full h-[90px] min-h-[80px] flex flex-row gap-5 overflow-x-auto p-2"
      hideScrollBar
    >
      {daysInMonth.map(({ day, weekday, weekdayName }, index) => (
        <Date
          numberDay={day}
          day={weekdayName}
          selected={index + 1 === selectedDay || day === selectedDay}
          weekDayNumber={weekday}
          changeSelected={(day: number) => setSelectedDay(day)}
          key={weekdayName + index}
        />
      ))}
    </ScrollShadow>
  );
}

export default function Body() {
  const [selectedDay] = useAtom(selectedDayAtom);
  const dataAuto = generarDatos(selectedDay);

  console.log(dataAuto);
  return (
    <section className="w-full h-4/5">
      <div className="bg-[#FEFFFE] w-full h-full rounded-tl-[50px] p-6 flex flex-col gap-5">
        <DatesContainer></DatesContainer>
        <EmployersTable people={dataAuto}></EmployersTable>
      </div>
    </section>
  );
}
